/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 4sje230Uy8kMHFtZigBaXvym2heuITcG7BwDGuIXNfTINjAkgvcu/N8yARblBtRm3AsFEbkV4mvWpovz+cYj5A==
 */

/* eslint-disable */
// tslint:disable

import Migrations, {Migrations_InsertParameters} from './migrations'
import Todo, {Todo_InsertParameters} from './todo'
import Todotype, {Todotype_InsertParameters} from './todotype'

interface DatabaseSchema {
  migrations: {record: Migrations, insert: Migrations_InsertParameters};
  todo: {record: Todo, insert: Todo_InsertParameters};
  todotype: {record: Todotype, insert: Todotype_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  Migrations,
  Migrations_InsertParameters,
  Todo,
  Todo_InsertParameters,
  Todotype,
  Todotype_InsertParameters,
}
