/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 9jFf8fEOnVgj9tsiQo0yN6DTRdtwEjxEfrXDEy5/N7Q18+uDZEgo2dEVg8wJxJ+UQvc2TH8kLYNY553SRWF8mA==
 */

/* eslint-disable */
// tslint:disable

interface Todo {
  description: (string) | null
  name: (string) | null
  /**
   * @default 0
   */
  status: (number) | null
}
export default Todo;

interface Todo_InsertParameters {
  description?: (string) | null
  name?: (string) | null
  /**
   * @default 0
   */
  status?: (number) | null
}
export type {Todo_InsertParameters}
