/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 0IP4VQ4mldQa7w4jK7AGoJjwNxGNu9dS5YTCrX/1sELVW+XnRTfM42Bdly+rSJ/ZzFFIwhXMx9elmRXQBW1kaA==
 */

/* eslint-disable */
// tslint:disable

interface Todotype {
  description: (string) | null
  /**
   * @default nextval('todotype_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'todotype_id'}
  name: (string) | null
  /**
   * @default true
   */
  status: boolean
}
export default Todotype;

interface Todotype_InsertParameters {
  description?: (string) | null
  /**
   * @default nextval('todotype_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'todotype_id'}
  name?: (string) | null
  /**
   * @default true
   */
  status?: boolean
}
export type {Todotype_InsertParameters}
